"""Prompt templates for DS-STAR agents."""

from .templates import (
    ANALYZER_SYSTEM,
    ANALYZER_USER,
    CODER_SYSTEM,
    CODER_USER,
    DEBUGGER_SYSTEM,
    DEBUGGER_USER,
    FINALIZER_SYSTEM,
    FINALIZER_USER,
    PLANNER_SYSTEM,
    PLANNER_USER,
    ROUTER_SYSTEM,
    ROUTER_USER,
    VERIFIER_SYSTEM,
    VERIFIER_USER,
)

__all__ = [
    "ANALYZER_SYSTEM",
    "ANALYZER_USER",
    "PLANNER_SYSTEM",
    "PLANNER_USER",
    "CODER_SYSTEM",
    "CODER_USER",
    "VERIFIER_SYSTEM",
    "VERIFIER_USER",
    "ROUTER_SYSTEM",
    "ROUTER_USER",
    "DEBUGGER_SYSTEM",
    "DEBUGGER_USER",
    "FINALIZER_SYSTEM",
    "FINALIZER_USER",
]
